export const tmpData = [
  {
    ID: "1",
    EmployeeID: "202",
    FirstName: "Rahul",
    LastName: "Sharma",
    Age: "25",
    Email: "rahul.sharma10@gmail.com",
  },
  {
    ID: "2",
    EmployeeID: "103",
    FirstName: "Venkat",
    LastName: "Raman",
    Age: "34",
    Email: "ramanvenkat300@gmail.com",
  },
  {
    ID: "3",
    EmployeeID: "401",
    FirstName: "Jason",
    LastName: "David",
    Age: "26",
    Email: "davidjason12@gmail.com",
  },
  {
    ID: "4",
    EmployeeID: "503",
    FirstName: "Carl",
    LastName: "Marx",
    Age: "33",
    Email: "carl.marx22@gmail.com",
  },
  {
    ID: "5",
    EmployeeID: "201",
    FirstName: "Ritu",
    LastName: "Dutt",
    Age: "27",
    Email: "ritudutt001@gmail.com",
  },
  {
    ID: "6",
    EmployeeID: "111",
    FirstName: "Ahmed",
    LastName: "Kabir",
    Age: "32",
    Email: "ahmedkabi360@gmail.com",
  },
  {
    ID: "7",
    EmployeeID: "304",
    FirstName: "Sam",
    LastName: "Benjamin",
    Age: "36",
    Email: "benjaminsam21@gmail.com",
  },
  {
    ID: "8",
    EmployeeID: "219",
    FirstName: "Mohammed",
    LastName: "Siraj",
    Age: "24",
    Email: "sirajmohammed333@gmail.com",
  },
  {
    ID: "9",
    EmployeeID: "416",
    FirstName: "Akshay",
    LastName: "Kumar",
    Age: "29",
    Email: "akshaykumar0000@gmail.com",
  },
  {
    ID: "10",
    EmployeeID: "100",
    FirstName: "Sanjay",
    LastName: "Ramaswamy",
    Age: "30",
    Email: "ramaswamy.sanjay401@gmail.com",
  },
];
